import test from 'node:test';import assert from 'node:assert/strict';
import{smoothStep,integrateMotion,normalizedInput,placeLabels}from'../dist/navigation.js';
const close=(a,b)=>assert.ok(Math.abs(a-b)<1e-8,`${a} != ${b}`);
function travel(fps){let velocity=0,distance=0;for(let i=0;i<fps;i++){const step=integrateMotion(velocity,30,9,1/fps);velocity=step.velocity;distance+=step.distance}for(let i=0;i<fps;i++){const step=integrateMotion(velocity,0,9,1/fps);velocity=step.velocity;distance+=step.distance}return{velocity,distance}}
test('acceleration and braking travel the same distance at 30, 60 and 144 FPS',()=>{const baseline=travel(60);for(const fps of[30,144]){const result=travel(fps);close(result.distance,baseline.distance);close(result.velocity,baseline.velocity)}});
test('camera smoothing converges without overshooting at variable frame times',()=>{let angle=0;for(const dt of[.01,.016,.033,.05,.01]){angle=smoothStep(angle,1,16,dt);assert.ok(angle>0&&angle<1)}close(smoothStep(1,1,16,.016),1)});
test('diagonal and three-axis flight do not exceed straight-line speed',()=>{for(const keys of[['w'],['w','d'],['w','d','e']]){const v=normalizedInput(new Set(keys));close(Math.hypot(v.x,v.y,v.z),1)}assert.deepEqual(normalizedInput(new Set(['w','s','a','d'])),{x:0,y:0,z:0})});
test('arrow keys are the primary flight mapping with page keys for vertical travel',()=>{assert.deepEqual(normalizedInput(new Set(['arrowup'])),{x:0,y:0,z:-1});assert.deepEqual(normalizedInput(new Set(['arrowdown'])),{x:0,y:0,z:1});assert.deepEqual(normalizedInput(new Set(['arrowleft'])),{x:-1,y:0,z:0});assert.deepEqual(normalizedInput(new Set(['arrowright'])),{x:1,y:0,z:0});assert.deepEqual(normalizedInput(new Set(['pageup'])),{x:0,y:1,z:0});assert.deepEqual(normalizedInput(new Set(['pagedown'])),{x:0,y:-1,z:0})});
test('coasting brakes to rest instead of continuing indefinitely',()=>{let v=70;for(let i=0;i<240;i++)v=integrateMotion(v,0,7,1/60).velocity;assert.ok(Math.abs(v)<1e-8)});
test('labels respect phone screen edges, overlays and collision limits',()=>{const placed=placeLabels([{i:0,x:180,y:320},{i:1,x:185,y:325},{i:2,x:10,y:350},{i:3,x:180,y:450},{i:4,x:180,y:100}],390,844,{mobile:true});assert.deepEqual(placed.map(x=>x.i),[0,3]);for(const c of placed){assert.ok(c.rect.left>=12&&c.rect.right<=378);assert.ok(c.rect.bottom<=624)}});
test('desktop intro and nearby panel stay clear of labels',()=>{const placed=placeLabels([{i:0,x:180,y:200},{i:1,x:750,y:300},{i:2,x:1200,y:650}],1440,900,{intro:true});assert.deepEqual(placed.map(x=>x.i),[1])});
